# Use postgres/example user/password credentials
version: "3.1"

services:
  airflow:
    image: puckel/docker-airflow
    ports:
      - 8080:8080
    command: webserver
    volumes:
      - .:/usr/local/airflow/dags
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: taxi_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
